type Criteria = {
  name?: string,
  dimensionA?: string,
  dimensionB?: string,
  dimensionC?: string,
  cost?: number,
  costLowerBound?: number,
  costUpperBound?: number,
  msrp?: number,
  msrpLowerBound?: number,
  msrpUpperBound?: number,
  margin?: number,
  marginLowerBound?: number,
  marginUpperBound?: number,
};